// T6 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool
#include maps\mp\animscripts\traverse\shared;
#include maps\mp\animscripts\traverse\zm_shared;

main()
{
    dosimpletraverse( "zombie_wall_crawl_drop_quick" );
}
