// T6 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool
#include common_scripts\utility;
#include maps\mp\_utility;
#include maps\mp\createfx\zm_moon_fx;
#include maps\mp\createart\zm_moon_art;

main()
{
    precache_createfx_fx();
    maps\mp\createfx\zm_moon_fx::main();
    maps\mp\createart\zm_moon_art::main();
    precache_scripted_fx();
    footsteps();
}

footsteps()
{

}

precache_scripted_fx()
{
    level._effect["large_ceiling_dust"] = loadfx( "env/zombie/fx_dust_ceiling_impact_lg_mdbrown" );
    level._effect["poltergeist"] = loadfx( "misc/fx_zombie_couch_effect" );
    level._effect["gasfire"] = loadfx( "destructibles/fx_dest_fire_vert" );
    level._effect["switch_sparks"] = loadfx( "env/electrical/fx_elec_wire_spark_burst" );
    level._effect["wire_sparks_oneshot"] = loadfx( "electrical/fx_elec_wire_spark_dl_oneshot" );
    level._effect["rise_burst"] = loadfx( "maps/zombie/fx_mp_zombie_hand_dirt_burst" );
    level._effect["rise_billow"] = loadfx( "maps/zombie/fx_mp_zombie_body_dirt_billowing" );
    level._effect["rise_dust"] = loadfx( "maps/zombie/fx_mp_zombie_body_dust_falling" );
    level._effect["airlock_fx"] = loadfx( "maps/zombie_moon/fx_moon_airlock_door_forcefield" );
    level._effect["rise_billow_lg"] = loadfx( "maps/zombie_moon/fx_moon_body_dirt_billowing" );
    level._effect["rise_dust_lg"] = loadfx( "maps/zombie_moon/fx_moon_body_dust_falling" );
    level._effect["rise_burst_lg"] = loadfx( "maps/zombie_moon/fx_moon_hand_dirt_burst" );
    level._effect["lght_marker"] = loadfx( "maps/zombie/fx_zombie_coast_marker" );
    level._effect["betty_explode"] = loadfx( "weapon/bouncing_betty/fx_explosion_betty_generic" );
    level._effect["betty_trail"] = loadfx( "weapon/bouncing_betty/fx_betty_trail" );
    level._effect["zapper_fx"] = loadfx( "maps/zombie/fx_zombie_zapper_powerbox_on" );
    level._effect["zapper"] = loadfx( "maps/zombie/fx_zombie_electric_trap" );
    level._effect["zapper_wall"] = loadfx( "maps/zombie/fx_zombie_zapper_wall_control_on" );
    level._effect["zapper_light_ready"] = loadfx( "maps/zombie/fx_zombie_zapper_light_green" );
    level._effect["zapper_light_notready"] = loadfx( "maps/zombie/fx_zombie_zapper_light_red" );
    level._effect["terminal_ready"] = loadfx( "maps/zombie_moon/fx_moon_trap_switch_light_on_green" );
    level._effect["elec_room_on"] = loadfx( "maps/zombie/fx_zombie_light_elec_room_on" );
    level._effect["elec_md"] = loadfx( "electrical/fx_elec_player_md" );
    level._effect["elec_sm"] = loadfx( "electrical/fx_elec_player_sm" );
    level._effect["elec_torso"] = loadfx( "electrical/fx_elec_player_torso" );
    level._effect["elec_trail_one_shot"] = loadfx( "maps/zombie/fx_zombie_elec_trail_oneshot" );
    level._effect["lght_marker_flare"] = loadfx( "maps/zombie/fx_zombie_coast_marker_fl" );
    level._effect["fx_quad_vent_break"] = loadfx( "maps/zombie/fx_zombie_crawler_vent_break" );
    level._effect["quad_grnd_dust_spwnr"] = loadfx( "maps/zombie/fx_zombie_crawler_grnd_dust_spwnr" );
    level._effect["fx_weak_sauce_trail"] = loadfx( "maps/zombie_temple/fx_ztem_weak_sauce_trail" );
    level._effect["soul_swap_trail"] = loadfx( "maps/zombie_moon/fx_moon_soul_swap" );
    level._effect["vrill_glow"] = loadfx( "maps/zombie_moon/fx_moon_vril_glow" );
    level._effect["jump_pad_active"] = loadfx( "maps/zombie_moon/fx_moon_jump_pad_on" );
    level._effect["jump_pad_jump"] = loadfx( "maps/zombie_moon/fx_moon_jump_pad_pulse" );
    level._effect["quad_phasing"] = loadfx( "maps/zombie_moon/fx_zombie_phasing" );
    level._effect["glass_impact"] = loadfx( "maps/zombie_moon/fx_moon_break_window" );
    level._effect["digger_treadfx_fwd"] = loadfx( "maps/zombie_moon/fx_digger_treadfx_fwd" );
    level._effect["digger_treadfx_bkwd"] = loadfx( "maps/zombie_moon/fx_digger_treadfx_rev" );
    level._effect["exca_beam"] = loadfx( "maps/zombie_moon/fx_digger_light_beam" );
    level._effect["exca_blink"] = loadfx( "maps/zombie_moon/fx_beacon_light_red" );
    level._effect["panel_on"] = loadfx( "maps/zombie_moon/fx_moon_digger_panel_on" );
    level._effect["panel_off"] = loadfx( "maps/zombie_moon/fx_moon_digger_panel_off" );
    level._effect["test_spin_fx"] = loadfx( "env/light/fx_light_warning" );
    level._effect["rocket_booster"] = loadfx( "maps/zombie_moon/fx_earth_destroy_rocket" );
    level._effect["blue_eyes"] = loadfx( "maps/zombie/fx_zombie_eye_single_blue" );
    level._effect["osc_button_glow"] = loadfx( "maps/zombie_moon/fx_moon_button_console_glow" );
}

precache_createfx_fx()
{
    level._effect["fx_mp_fog_xsm_int"] = loadfx( "maps/zombie_old/fx_mp_fog_xsm_int" );
    level._effect["fx_moon_fog_spawn_closet"] = loadfx( "maps/zombie_moon/fx_moon_fog_spawn_closet" );
    level._effect["fx_zmb_fog_thick_300x300"] = loadfx( "maps/zombie/fx_zmb_fog_thick_300x300" );
    level._effect["fx_zmb_fog_thick_600x600"] = loadfx( "maps/zombie/fx_zmb_fog_thick_600x600" );
    level._effect["fx_moon_fog_canyon"] = loadfx( "maps/zombie_moon/fx_moon_fog_canyon" );
    level._effect["fx_moon_vent_wall_mist"] = loadfx( "maps/zombie_moon/fx_moon_vent_wall_mist" );
    level._effect["fx_dust_motes_blowing"] = loadfx( "env/debris/fx_dust_motes_blowing" );
    level._effect["fx_zmb_coast_sparks_int_runner"] = loadfx( "maps/zombie/fx_zmb_coast_sparks_int_runner" );
    level._effect["fx_moon_floodlight_narrow"] = loadfx( "maps/zombie_moon/fx_moon_floodlight_narrow" );
    level._effect["fx_moon_floodlight_wide"] = loadfx( "maps/zombie_moon/fx_moon_floodlight_wide" );
    level._effect["fx_moon_tube_light"] = loadfx( "maps/zombie_moon/fx_moon_tube_light" );
    level._effect["fx_moon_lamp_glow"] = loadfx( "maps/zombie_moon/fx_moon_lamp_glow" );
    level._effect["fx_moon_trap_switch_light_glow"] = loadfx( "maps/zombie_moon/fx_moon_trap_switch_light_glow" );
    level._effect["fx_moon_teleporter_beam"] = loadfx( "maps/zombie_moon/fx_moon_teleporter_beam" );
    level._effect["fx_moon_teleporter_start"] = loadfx( "maps/zombie_moon/fx_moon_teleporter_start" );
    level._effect["fx_moon_teleporter_pad_start"] = loadfx( "maps/zombie_moon/fx_moon_teleporter_pad_start" );
    level._effect["fx_moon_teleporter2_beam"] = loadfx( "maps/zombie_moon/fx_moon_teleporter2_beam" );
    level._effect["fx_moon_teleporter2_pad_start"] = loadfx( "maps/zombie_moon/fx_moon_teleporter2_pad_start" );
    level._effect["fx_moon_pyramid_egg"] = loadfx( "maps/zombie_moon/fx_moon_pyramid_egg" );
    level._effect["fx_moon_pyramid_drop"] = loadfx( "maps/zombie_moon/fx_moon_pyramid_drop" );
    level._effect["fx_moon_pyramid_opening"] = loadfx( "maps/zombie_moon/fx_moon_pyramid_opening" );
    level._effect["fx_moon_ceiling_cave_dust"] = loadfx( "maps/zombie_moon/fx_moon_ceiling_cave_dust" );
    level._effect["fx_moon_ceiling_cave_collapse"] = loadfx( "maps/zombie_moon/fx_moon_ceiling_cave_collapse" );
    level._effect["fx_moon_digger_dig_dust"] = loadfx( "maps/zombie_moon/fx_moon_digger_dig_dust" );
    level._effect["fx_moon_airlock_hatch_forcefield"] = loadfx( "maps/zombie_moon/fx_moon_airlock_hatch_forcefield" );
    level._effect["fx_moon_biodome_ceiling_breach"] = loadfx( "maps/zombie_moon/fx_moon_biodome_ceiling_breach" );
    level._effect["fx_moon_biodome_breach_dirt"] = loadfx( "maps/zombie_moon/fx_moon_biodome_breach_dirt" );
    level._effect["fx_moon_breach_debris_room_os"] = loadfx( "maps/zombie_moon/fx_moon_breach_debris_room_os" );
    level._effect["fx_moon_breach_debris_out_os"] = loadfx( "maps/zombie_moon/fx_moon_breach_debris_out_os" );
    level._effect["fx_earth_destroyed"] = loadfx( "maps/zombie_moon/fx_earth_destroyed" );
}
