// T6 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    self setmodel( "c_jap_takeo_body" );
    self.voice = "american";
    self.skeleton = "base";
}

precache()
{
    precachemodel( "c_jap_takeo_body" );
}
